version: 0.2

env:
  variables:
    AWS_REGION: us-east-1

phases:
  install:
    commands:
      - terraform version
  build:
    commands:
      - terrform init
      - terraform plan
      - terraform deploy -auto-approve
