version: 0.2

env:
  variables:
    FOO: BAR
    TERRAFORM_VERSION: 0.13.5

phases:
  install:
    commands:
      - terraform version
  build:
    commands:
      - terraform plan
      - terraform deploy -auto-approve
