name: Terraform

on:
  pull_request: []
  push:
    branches:
      - main

jobs:
  lint:
    name: "🧹 Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@latest

      - name: Terraform Format
        run: terraform fmt -check
